layout: sidebar
style: dark
encoding: UTF-8
url: "https://notmahi.gitlab.io"
baseurl: ""
repository: notmahi/notmahi.github.io

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-sitemap
  - jekyll-feed

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

include: ['_pages']

collections:
  - galleries

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 15
  exclude:
    archived: false
    forks: true
    projects:
    - Minify
    - marvin
    - Manga.py
    - learned-k-server
    - hierarchical-abm
    - covid19-r-simulations-lancet
    - puntender
    - uptime
    # - notmahi/bd-rt-dashboard
    # - d3-books-timeline

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # youtube: your_username
  scholar: vAOw6aQAAAAJ
  linkedin: nshafiul
  twitter: notmahi
  keybase: mahi
  instagram: thesecondsonofman
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  website: http://mahis.life

topics:
  - name: Deep Learning
    web_url: https://github.com/topics/deep-learning
    image_url: /assets/images/icons/icons8-deep-learning-64.png

  - name: Robotics
    web_url: https://lerrelpinto.com
    image_url: /assets/images/icons/icons8-robot-120.png

  - name: Data Visualization
    web_url: https://notmahi.github.io/d3-book-timeline/
    image_url: /assets/images/icons/icons8-data-visualization-64.png

  - name: Reading
    web_url: https://www.goodreads.com/shafiullah
    image_url: /assets/images/icons/icons8-books-64.png

  - name: Photography and Writing
    web_url: https://thetech.com/photographers/mahi-shafiullah
    image_url: /assets/images/icons/icons8-photography-64.png

  - name: Philosophy
    web_url: https://plato.stanford.edu/
    image_url: /assets/images/icons/icons8-philosophy-100.png

quotes: true
