layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: thesecondsonofman
  keybase: mahi
  linkedin: nshafiul
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: notmahi
  # unsplash: your_username
  # vk: your_username
  website: http://mahis.life
  # youtube: your_username

topics:
  - name: Deep Learning
    web_url: https://github.com/topics/deep-learning
    image_url: https://upload.wikimedia.org/wikipedia/commons/7/7a/Anatomy-1751201_1280.png

  - name: Robotics

  - name: COVID-19
    web_url: https://github.com/topics/covid-19
    image_url: https://raw.githubusercontent.com/github/explore/af16e074f93c080d7b283815787283cab0e9414b/topics/covid-19/covid-19.png
