layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # youtube: your_username
  scholar: vAOw6aQAAAAJ
  linkedin: nshafiul
  twitter: notmahi
  keybase: mahi
  instagram: thesecondsonofman
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  website: http://mahis.life

topics:
  - name: Deep Learning
    web_url: https://github.com/topics/deep-learning
    image_url: /assets/images/icons8-deep-learning-64.png

  - name: Robotics
    web_url: https://lerrelpinto.com
    image_url: /assets/images/icons8-robot-120.png

  - name: Data Visualization
    web_url: https://notmahi.github.io/d3-book-timeline/
    image_url: /assets/images/icons8-data-visualization-64.png

  - name: Reading
    web_url: https://www.goodreads.com/shafiullah
    image_url: /assets/images/icons8-books-64.png

  - name: Photography and Writing
    web_url: https://thetech.com/photographers/mahi-shafiullah
    image_url: /assets/images/icons8-photography-64.png

  - name: Philosophy
    web_url: https://plato.stanford.edu/
    image_url: /assets/images/icons8-philosophy-100.png
