name: Refresh

on:
  schedule:
    - cron:  '0 4 * * 0/3' # At 04:00 on every 3rd day-of-week from Sunday through Sunday.

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Authorization: Bearer $USER_TOKEN" \
          --url https://api.github.com/repos/${{ github.repository }}/pages/builds
        env:
          # You must create a personal token with repo access as GitHub does
          # not yet support server-to-server page builds.
          USER_TOKEN: ${{ secrets.USER_PAT_BUILD }}
